### ISSUE TITLE
Tracking issue: local mode for Qdrant v1.8

### ISSUE THREAD

**Issue by coszio** [qdrant/qdrant-client#490]
There are some new features scheduled for Qdrant v1.8 that need to be implemented in local mode:

- [x] `order_by` in scroll (qdrant/qdrant#3521) => #491 
- [x] `min_should` filtering condition (qdrant/qdrant#3466) => no PR yet
- [x] remove deprecated `clear_payload_deprecated` field => #502
    - https://github.com/qdrant/qdrant-client/blob/66cb6dff45a98d915e572d35a46e2e6e9d9c3b0c/tests/conversions/fixtures.py#L801

**Comment by generall** [comment]
- [ ] Support for datetime

**Comment by generall** [comment]
- [ ] API for checking if collection exists: https://github.com/qdrant/qdrant/pull/3472

**Comment by joein** [comment]
- [] update fastembed integration https://github.com/qdrant/qdrant-client/pull/493
